schemaVersion: 2.2.2
metadata:
  attributes:
    metadata-name-field: generateName
    metadata-name-original-value: cleverclient
  name: cleverclient
  namespace: sashirestela-dev
attributes:
  che-theia.eclipse.org/sidecar-policy: mergeImage
projects:
  - name: cleverclient
    git:
      remotes:
        origin: https://github.com/sashirestela/cleverclient.git
components:
  - name: universal-developer-image
    container:
      image: quay.io/devfile/universal-developer-image:ubi8-latest
      volumeMounts:
        - name: m2
          path: /home/user/.m2
      mountSources: true
  - name: m2
    volume:
      size: 5Gi
commands: []